defaults: &defaults
  docker:
    - image: circleci/python:3.6

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
  coverage:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Prepare Tests
          command: cc-test-reporter before-build

      - run:
          name: Run Tests
          command: |
            coverage run runtests.py

#      - run:
#          name: Aggregate Code Coverage
#          command: |
#            docker cp app_coverage_run_1:/opt/coverage.xml .
#            sed -ie 's/\/opt/src/g' coverage.xml
#            cc-test-reporter after-build --coverage-input-type coverage.py --exit-code $?

